### ISSUE TITLE
Can you add WEB REPUTATION and TALOS SECURITY INTELLIGENCE BLACKLIST CLASSIFICATION

### ISSUE THREAD

**Issue by ksmaheshkumar** [cescobarresi/ciscoreputation#4]
Hi,
can you add WEB REPUTATION and TALOS SECURITY INTELLIGENCE BLACKLIST's CLASSIFICATION with this.

**Comment by cescobarresi** [comment]
Hi there,
I finally added the WEB REPUTATION and TALOS SECURITY INTELLIGENCE BLACKLIST. The latter just as a "Yes" or "No" flag. I may added more detailed info later.
You can check it out in v2.1.2
